services:
  app:
    build: .
    ports:
      - 127.0.0.1:5000:5000
    working_dir: /swara-server
    depends_on:
      - postgres
    env_file: ./.env
    environment:
      DATABASE_URL: $DATABASE_URL
      PORT: 5000
    volumes:
      - .:/swara-server
      - /swara-server/node_modules

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file: ./.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
volumes:
  postgres_volume:
